# More information on the parameters can be found here: https://documentation.red-gate.com/flyway/reference/configuration

[environments.default]
url = "jdbc:bigquery://https://www.googleapis.com/bigquery/v2:443;OAuthType=3;ProjectId=elite-caster-125113;"
user = ""
password = ""
# driver =
schemas = ["dsongcp"]
# connectRetries =
# connectRetriesInterval =
# initSql =
# jdbcProperties =
# resolvers =

[flyway]
# environment = "sample" # It is recommended to configure environment as a commandline argument. This allows using different environments depending on the caller.
locations = ["filesystem:migrations"]
validateMigrationNaming = true
cleanDisabled = false
# jarDirs = ["path/to/java/migrations"]

# [environments.build]
# url = "jdbc:sqlite::memory:"
# user = "buildUser"
# password = "buildPassword"

# [flyway.check]
# buildEnvironment = "build"